renaming to overnode

diff --git a/install.sh.template b/install.sh.template
--- a/install.sh.template
+++ b/install.sh.template
@@ -1,13 +1,24 @@
 #!/usr/bin/env sh
 
-#
-# License: https://github.com/cadeworks/cade/blob/master/LICENSE
-#
-
 set -e
 
-version_system=${cade_release_version}
-wget --no-cache -O /usr/bin/cade https://raw.githubusercontent.com/cadeworks/cade/${cade_release_version}/cade.sh
-chmod a+x /usr/bin/cade
+wget --no-cache -O /tmp/overnode https://raw.githubusercontent.com/avkonst/overnode/${overnode_release_version}/overnode.sh
+chmod a+x /tmp/overnode
 
-cade --debug version || (echo "cade installation failed" && exit 1)
+/tmp/overnode --debug version || (echo "overnode download failed" && exit 1)
+
+if [ ! -f /usr/bin/overnode ]
+then
+    overnode install
+    mv /tmp/overnode /usr/bin/overnode || (echo "overnode install failed" && exit 1)
+else
+    if [ $# -eq 0 ]
+    then
+        echo "/usr/bin/overnode file exists already"
+        echo "run this script with --force flag to initiate the upgrade"
+    else
+        /tmp/overnode install --force
+        mv /tmp/overnode /usr/bin/overnode || (echo "overnode upgrade failed" && exit 1)
+    fi
+fi
+
